# Generated by Django 4.1.5 on 2023-02-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_project',
            field=models.CharField(choices=[('colon', 'colon'), ('row', 'row')], max_length=100),
        ),
    ]
