# Generated by Django 4.1.5 on 2023-02-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_type_of_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type_of_project',
        ),
    ]
